#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Verifica se há lacunas nos elementos do arquivo alvo e abre o prompt input.

Usage:
    fill-gaps <arquivo>

Options:
    --version

"""

import os

from docopt import docopt
from subprocess import getoutput
from modulos.py_sps_cli_base import data_folder
from modulos.py_console_tools import save_json, load_json, limpar_tela

args = docopt(__doc__)

def fill_gaps(arquivo):
    arquivo_nfo = load_json(os.sep.join([data_folder, arquivo]))
    for linha in arquivo_nfo:
        for coluna in linha.keys():
            if linha[coluna] == "":
                limpar_tela()
                print(linha)
                linha[coluna] = input(coluna+': ')
        save_json(arquivo_nfo, os.sep.join([data_folder, arquivo]))


def main():
    fill_gaps(args["<arquivo>"])


if __name__ == '__main__':
    main()