#!/usr/bin/env python3
# -*- coding: utf-8 -*-

cmd_nfo="Lê informações do arquivo '.current_target'"

import argparse

from py_console_tools_v0 import load_json

parser = argparse.ArgumentParser(description=cmd_nfo)
parser.add_argument("chave", help="indique a chave a ser recuperada...")
args = parser.parse_args()

def main():
    current_target = load_json('./.current_target')
    return current_target.get(args.chave)
 

if __name__ == '__main__':
	print(main())


