#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Baixa todos os fragmentos da nuvem 'box' para a pasta dados/fragmentos

Usage:
    getfrags 

Options:
    --version

"""

from os import system, fork, listdir
from modulos.py_sps_cli_base import security_folder, user_home_folder, fragmentos_folder

from docopt import docopt

args = docopt(__doc__)


def getfrags():
    system('cp "{}/rclone-token" "{}/.rclone.conf"'.format(security_folder, user_home_folder))
    system("rclone copy box:/sps_fup2/ {}".format(fragmentos_folder))
    system('rm "{}/.rclone.conf"'.format(user_home_folder))
    fragfiles = listdir(fragmentos_folder)
    for f in fragfiles:
        if f.find('.cpt') != -1:
            system("sps-decrypt {}/{}".format(fragmentos_folder, f))


if __name__ == '__main__':
    newpid = fork()
    if newpid == 0:
        getfrags()
