#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Busca as informações registradas no índice do banco de dados para todos os arquivos de dados...

Usage:
    getnfo ( <identificador> ) 

Options:
    --version

"""

import os

from docopt import docopt
from subprocess import getoutput
from modulos.py_sps_cli_base import\
    dados_usuarios,\
    dados_processos,\
    dados_atendimentos,\
    dados_corrigidos,\
    dados_index
    
from modulos.py_console_tools_v0 import save_json, verde, saida_verde

args = docopt(__doc__)

def get_nfo(identificador, set_de_dados, index_de_dados=dados_index):
    for s in index_de_dados:
        if s['set_de_dados'] == set_de_dados:
            return s['dados'].get(identificador)

def show_nfo_frag(identificador, set_de_dados, db):
    ret_nfo = get_nfo(identificador, set_de_dados)
    if ret_nfo:
        for i in ret_nfo:
            print(db[i])


def main():
    if args["<identificador>"].find('@') != -1:
        show_nfo_frag(args["<identificador>"], 'est-eml', dados_usuarios)
        
    elif args["<identificador>"].find('/') != -1:
        print(verde("Dados pessoais"))
        show_nfo_frag(args["<identificador>"], 'est', dados_usuarios)
        print("")
        print(verde("Dados de atendimentos"))
        show_nfo_frag(args["<identificador>"], 'atd', dados_atendimentos)
        print("")
        print(verde("Dados de processos"))
        show_nfo_frag(args["<identificador>"], 'proc', dados_processos)


if __name__ == '__main__':
    main()