#!/bin/bash
#
#

OUTPUT=""
cat < /home/bwb0de/Devel/sps_fup2/dados/atendimentos.json > /tmp/cmd_get_data
while read p;
do
    if [ $(echo $p | grep "identificador" | wc -l) -eq 1 ];
    then
        IDENTIFICADOR=$(echo $p | tr ',' ' ' | tr '"' ' ' | awk -F": " '{ print $2 }' );
        OUTPUT=$(echo "$OUTPUT $IDENTIFICADOR \n")
    fi;
done < /tmp/cmd_get_data
echo $OUTPUT