#!/usr/bin/env python3
# -*- coding: utf-8 -*-

cmd_nfo="Lista informações do banco de dados"

import argparse

from subprocess import check_output
from py_sps_cli_base import *

parser = argparse.ArgumentParser(description=cmd_nfo)
parser.add_argument("action", help="utilize uma: atd|est|prof|esoc|corr|mat")
parser.add_argument("-m", help="lista estudantes que possuam o marcador")
args = parser.parse_args()

def main():
    if args.action == 'atd':
        print("Listando atendimentos realizados:")
        return listar_dicionario(dados_atendimentos, [col_width_atend_time, col_width_atend_ident, ('atd_t', 0)])

    elif args.action == 'est':
        print("Listando informações dos usuários:")
        if args.m != None:
            marcador = args.m
            return listar_dicionario(dados_estudantes, [col_width_etd_mat, col_width_etd_nome, col_width_etd_eml], [marcador])
        else:
            return listar_dicionario(dados_estudantes, [col_width_etd_mat, col_width_etd_nome, col_width_etd_eml])

    elif args.action == 'prof':
        print("Listando profissionais cadastrados:")
        return listar_dicionario(dados_profissionais, [col_width_prof_uid, col_width_prof_nome, col_width_prof_eml])

    elif args.action == 'esoc':
        print("Listando estudo socioeconômico:")
        pass

    elif args.action == 'corr':
        print("Listando informações sobre correções dos estudo socioeconômico:")
        pass

    elif args.action == 'proc':
        print("Listando todos processos:")
        return listar_dicionario(dados_processos, [col_width_etd_mat, col_width_proc_sei_n, col_width_proc_motivo, col_width_proc_assunto])

    elif args.action == 'procp':
        print("Listando processos pendentes:")
        return listar_dicionario(dados_processos_pend, [col_width_etd_mat, col_width_proc_sei_n, col_width_proc_assunto])

    elif args.action == 'mat':
        return get_mat(dados_estudantes)


if __name__ == '__main__':
	print(main(), os.linesep)
