#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Adiniona novos registros nos arquivos de dados.

Usage:
    novo ( usr | usuario ) <identificador>
    novo ( atd | atendimento ) <identificador>
    novo ( sei | processo ) <identificador> <assunto>
    novo ( res | resposta-de-processo )
    novo ( est | estudo ) <identificador>
    novo ( pro | profissional ) <uid>
    novo ( dbc | campo-db ) <arquivo_db> <coluna> [<lista-ops>] 
    novo ( dbi | inserir-form-info ) ( mesclado | aninhado ) <arquivo_db> <formulario> 
    novo ( opt | inserir-op) <coluna> <opcao> <formulario>

Options:
    --version

Observações:
    A opção <lista-ops> pode ser separada por ';' para criar um campo de múltipla escolha.
    O comando 'dbi' insere as respostas de um formulário¹ em um arquivo de dados JSON já criado.
    O comando 'opt' insere uma alternativa ao campo de multipla escolha indicado de um formulário.
    Apenas 'root' pode executar os comandos 'pro' e 'tgr'.

¹Estrutura do arquivo de formulário:
	{
		"titulo": "Registro de atendimento",
		"descricao": "Intrumental para registro de atendimentos no âmbito do SPS/FUP",
		"questoes":
		[
			{
				"enunciado": "Matrícula",
				"id": "identificador",
				"tipo": "text",
			},
			{
				"enunciado": "Tipo de atendimento",
				"id": "atd_t",
				"tipo": "checkbox",
				"alternativas" :
				[
					"Informação presencial",
					"Informação via telefone",
					"Outro"²
				]            
			}
		]
	}	

²A inclusão da opção 'Outro' permite a insersão dinâmica de outros valores no formulário

"""


import getpass
import os

from docopt import docopt
from subprocess import getoutput
from modulos.py_sps_cli_base import save_target_info, get_mat, timestamp, data_folder, numero_sei_mascara, numero_identificador_mascara,\
    form_novo_usuario, dados_usuarios, arquivo_usuarios,\
    form_processos, dados_processos, arquivo_processos,\
    form_atendiento, dados_atendimentos, arquivo_atendimentos,\
    form_corrigidos, dados_corrigidos, arquivo_corrigidos,\
    form_estudo_info_estudante,\
    form_estudo_info_familia,\
    form_estudo_info_membros_familia,\
    dados_estudo_estudante, arquivo_estudo_estudante,\
    dados_estudo_familia, arquivo_estudo_familia,\
    dados_estudo_membros_familia, arquivo_estudo_membros_familia,\
    arquivo_index, automail, periodo_corrente, dados_index
    
from modulos.py_json_handlers import save_json, load_json
from modulos.py_console_tools import select_op, select_ops
from modulos.py_data_tools import render_form_get_values


args = docopt(__doc__)


matriculas = get_mat(dados_usuarios)

def novo_usuario(identificador):
    nfo = render_form_get_values(form_novo_usuario, ['identificador'])
    nfo['identificador'] = identificador
    dados_usuarios.append(nfo)
    save_json(dados_usuarios, arquivo_usuarios)

def novo_processo(identificador, assunto):
    nfo = render_form_get_values(form_processos, ['identificador'])
    nfo['timestamp'] = timestamp() 
    nfo['identificador'] = identificador
    nfo['assunto'] = assunto
    nfo['resultado'] = ''
    nfo['numero_sei'] = numero_sei_mascara(nfo['numero_sei'])
    dados_processos.append(nfo)
    save_json(dados_processos, arquivo_processos)
    return nfo['numero_sei']

def novo_resultado_processo(processo_num):
    for proc in dados_processos:
        if proc['numero_sei'] == processo_num:
            pass
    
def novo_atendimento(identificador):
    save_target_action = False
    if not identificador in matriculas:
        novo_usuario(identificador)
        matriculas.append(identificador)
        save_target_action = True
    nfo = render_form_get_values(form_atendiento, ['identificador'])
    nfo['timestamp'] = timestamp() 
    nfo['identificador'] = identificador
    nfo['prof_atd'] = getoutput("whoami")
    dados_atendimentos.append(nfo)
    if save_target_action == True:
        save_target_info(identificador)
    save_json(dados_atendimentos, arquivo_atendimentos)
    return nfo['atd_t']


def nova_correcao(identificador):
    nfo = render_form_get_values(form_corrigidos, ['identificador'])
    nfo['timestamp'] = timestamp() 
    nfo['identificador'] = identificador
    if not identificador in matriculas:
        novo_usuario(identificador)
        matriculas.append(identificador)    
    dados_corrigidos.append(nfo)
    save_json(dados_corrigidos, arquivo_corrigidos)

def nova_coluna(nome_col, json_file, options=None):
    db_file = load_json(os.sep.join([data_folder, json_file]))
    if options != None and options.find(";") != -1:
        opz = options.split(';')
        selection = True
    else:
        opz = options
        selection = False
    for i in db_file:
        if i.get(nome_col) == None and selection == True:
            for col in i.keys():
                print(col, ' -> ', i[col])
            nova_col_nfo = select_ops(opz, 1)
            if len(nova_col_nfo) > 1:
                i[nome_col] = '; '.join(nova_col_nfo)
            else:
                i[nome_col] = nova_col_nfo[0]
        elif i.get(nome_col) == None and selection == False:
            if options == None:
                i[nome_col] = input(str(nome_col)+': ')
            else:
                i[nome_col] = opz
        save_json(db_file, os.sep.join([data_folder, json_file]))

def novo_estudo_info_estudante(identificador):
    nfo = {}
    nfo['semestre'] = periodo_corrente
    nfo['identificador'] = identificador
    nfo['estudo_id'] = timestamp('mkid')
    if not identificador in matriculas:
        novo_usuario(identificador)
        matriculas.append(identificador)
    nfo_tmp = render_form_get_values(form_estudo_info_estudante, ['identificador'])
    for col in nfo_tmp.keys():
        nfo[col] = nfo_tmp[col]
    del(nfo_tmp)
    dados_estudo_estudante.append(nfo)
    save_json(dados_estudo_estudante, arquivo_estudo_estudante)
    return nfo['estudo_id']


def novo_estudo_info_familia(identificador, estudo_id):
    nfo_tmp = render_form_get_values(form_estudo_info_familia, ['identificador'])
    nfo = {}
    for set_de_dados in dados_index:
        if set_de_dados['set_de_dados'] == 'estudo':
            nfo = dados_estudo_estudante[set_de_dados['dados'][estudo_id]]
            break
    for col in nfo_tmp.keys():
        nfo[col] = nfo_tmp[col]
    del(nfo_tmp)
    save_json(dados_estudo_estudante, arquivo_estudo_estudante)


def novo_estudo_info_membros_familia(identificador, estudo_id):
    nfo = render_form_get_values(form_estudo_info_membros_familia, ['identificador'])
    nfo['identificador'] = identificador
    nfo['estudo_id'] = estudo_id
    save_json(dados_estudo_membros_familia, arquivo_estudo_membros_familia)

def novo_profissional():
    profissional = input('Definir a ID de login: ')
    print('Selecione a especialidade do/a profissional: ')
    especialidade = select_op(['Assistente Social', 'Administrador', 'Administradora', 'Assistente Administrativo', 'Estatístico', 'Estatística', 'Pedagogo', 'Pedagoga', 'Psicólogo', 'Psicóloga', 'Técnico em assuntos educacionais', 'Técnica em assuntos educacionais'], 1, sort_list=True) 
    sigla_conselho = input('Qual a sigla do conselho profissional: ')
    numero_no_concelho = input('Qual a matrícula frente ao conselho profissional: ')
    matricula_instituicao = input('Qual a matrícula institucional: ')
    getoutput('adduser {}'.format(profissional))
    prof_nfo = {}
    prof_nfo['uid'] = profissional
    prof_nfo['eml'] = input('Endereço de email institucional: ')
    prof_nfo['eml_server'] = "mail.unb.br"
    prof_nfo['eml_port'] = "587"
    while True:
        prof_nfo['eml_pwd'] = getpass.getpass('Insira a senha de acesso ao email institucional: ')
        verificar_senha = getpass.getpass('Insira, novamente, a senha do email institucional: ')
        if prof_nfo['eml_pwd'] == verificar_senha:
            prof_nfo['eml_pwd'] = getoutput('echo {} | base64'.format(prof_nfo['eml_pwd']))
            break
    prof_nfo['nome'] = getoutput("getent passwd | grep %s | awk -F: ' { print $5 } ' " % profissional).split(',')[0]
    prof_nfo['cargo'] = especialidade
    prof_nfo['matricula_conselho'] = numero_no_concelho
    prof_nfo['matricula_institucional'] = matricula_instituicao
    prof_nfo['eml_assinatura'] = "Atenciosamente,\n---\n{nome}\n{cargo}\n{conselho} {matricula_conselho}\nFUB {matricula_fub}".format(nome=prof_nfo['nome'], cargo=especialidade, conselho=sigla_conselho, matricula_conselho=numero_no_concelho, matricula_fub=matricula_instituicao)
    dados_profissionais.append(prof_nfo)
    save_json(dados_profissionais, arquivo_profissionais)    

def insert_info(json_estudantes, print_fields, formulario_q_add, novo_nome_de_campo):
    #insert_info('Consultas_OldSAE.json', ['identificador','Nome','Periodo','Data de Nascimento'], 'form_estudo_socioeconomico.json', 'Estudo Social e Economico')
    estudantes = load_json('./{}'.format(json_estudantes))
    novas_questoes = load_json('./forms/{}'.format(formulario_q_add))
    for e in estudantes:
        print(e)
        if e.get(novo_nome_de_campo) == None:
            limpar_tela()
            print_nfo = ""
            for f in print_fields:
                print_nfo += e[f] + os.linesep
            print(print_nfo)
            nfo = render_form_get_values(novas_questoes)
            e[novo_nome_de_campo] = nfo
            save_json(estudantes, './{}'.format(json_estudantes))


def main():
    if args['usr'] or args['usuario']:
        identificador = numero_identificador_mascara(args['<identificador>'])
        novo_usuario(identificador)
        matriculas.append(identificador)

    elif args['atd'] or args['atendimento']:
        identificador = numero_identificador_mascara(args['<identificador>'])
        save_target_info(identificador)
        atd_t = novo_atendimento(identificador)
        if atd_t == "Encaminhamento de pedido de auxílio emergencial":
            numero_sei = novo_processo(identificador, atd_t)
            if automail:
                os.system('sps-api insert -tp atendimentos.json "identificador::{}" "procedimento::{}" "atd_t::{}" "resultado::{}"'.format(identificador, "Atendimento via e-mail", "Envio de número de processo", "Verificar status de envio de email..."))
                os.system('echo "{numero_sei}" | sendeml get "$(target get eml)" "Assistência Estudantil - Processo de Auxílio Emergencial" "Segue o número do processo para acompanhamento do resultado. Com este número você pode consultar o resultado com qualquer pessoa do SPS que possua acesso ao SEI."'.format(numero_sei=numero_sei))

        elif atd_t == "Solicitação de acesso extraordinário ao RU":
            numero_sei = novo_processo(identificador, atd_t)
            if automail:
                os.system('echo "{numero_sei}" | sendeml get "$(target get eml)" "Assistência Estudantil - Processo de Acesso ao RU" "Segue o número do processo para que você possa acompanhar do resultado. Com este número você pode consultar o resultado junto a qualquer pessoa do SPS que possua acesso ao SEI."'.format(numero_sei=numero_sei))
                os.system('sps-api insert -tp atendimentos.json "identificador::{}" "procedimento::{}" "atd_t::{}" "resultado::{}"'.format(identificador, "Atendimento via e-mail", "Envio de número de processo", "Verificar status de envio de email..."))

        elif atd_t == "Recebimento/digiralização de pedido de recurso ao resultado da avaliação socioeconômica":
            numero_sei = novo_processo(identificador, atd_t)
            if automail:
                os.system('echo "{numero_sei}" | sendeml get "$(target get eml)" "Assistência Estudantil - Processo de Recurso à Avaliação Socioeconômica" "Segue o númro do processo de recurso. Se até a data prevista para o resultado você não obtiver resposta, vá ao SPS, forneça este número e informe a pendência."'.format(numero_sei=numero_sei))
                os.system('sps-api insert -tp atendimentos.json "identificador::{}" "procedimento::{}" "atd_t::{}" "resultado::{}"'.format(identificador, "Atendimento via e-mail", "Envio de número de processo", "Verificar status de envio de email..."))

    elif args['sei'] or args['processo']:
        identificador = numero_identificador_mascara(args['<identificador>'])
        novo_processo(identificador, args['<assunto>'])

    elif args['est'] or args['estudo']:
        identificador = numero_identificador_mascara(args['<identificador>'])
        estudo_id = novo_estudo_info_estudante(identificador)
        os.system("indexdb")
        novo_estudo_info_familia(identificador, estudo_id)
        print("Outras pessoas constituem o seu grupo familiar além de você?")
        resposta = select_op(["Sim", "Não"], 1)
        while resposta == "Sim":
            novo_estudo_info_membros_familia(identificador, estudo_id)
            print("Registrar outra pessoa?")
            resposta = select_op(["Sim", "Não"], 1)            


    elif args['pro'] or args['profissional']:
        if getoutput('whoami') != 'root':
            print("Apenas o usuário 'root' pode adicionar outros profissionais...")
        else:
            novo_profissional()

    elif args['dbc'] or args['campo-db']:
        nova_coluna(args['<coluna>'], args['<arquivo_db>'], args['<lista-ops>'])

    elif args['dbi'] or args['inserir-form-info']:
        pass
        
if __name__ == '__main__':
    cmd = main()
    newpid = os.fork()
    if newpid == 0:
        os.system("indexdb")