#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Criptografa e envia arquivo alvo para nuvem: 'box'.

Usage:
    sendfrag <arquivo>

Options:
    --version

"""

from os import system, fork
from modulos.py_sps_cli_base import security_folder, user_home_folder

from docopt import docopt

args = docopt(__doc__)

def sendfrag(arquivo):
    system("sps-encrypt {}".format(arquivo))
    arquivo_criptografado = arquivo + '.cpt'
    system('cp "{}/rclone-token" "{}/.rclone.conf"'.format(security_folder, user_home_folder))
    system("rclone copy {} box:/sps_fup2/".format(arquivo_criptografado))
    system('rm "{}/.rclone.conf"'.format(user_home_folder))
    system("sps-decrypt {}".format(arquivo_criptografado))


if __name__ == '__main__':
    newpid = fork()
    if newpid == 0:
        sendfrag(args["<arquivo>"])
