#!/usr/bin/env python3
# -*- coding: utf-8 -*-

cmd_nfo="Insere informações no arquivo '.current_target'"

import argparse
import os

from py_console_tools_v0 import load_json, save_json
from py_sps_cli_base import user_home_folder

parser = argparse.ArgumentParser(description=cmd_nfo)
parser.add_argument("chave", help="define um nome para o campo a ser inserido")
parser.add_argument("valor", help="atribui um valor ao campo")
args = parser.parse_args()

def main():
    current_target = load_json(os.sep.join([user_home_folder, '.current_target']))
    current_target[args.chave] = args.valor
    save_json(current_target, os.sep.join([user_home_folder, '.current_target']))
 
if __name__ == '__main__':
	main()


