#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Inicia menu para acesso às funcionalidades do ecosistema.

Usage:
    sps-menu 

"""

from docopt import docopt
from python_modules.cli_decorators import check_config_existance
from python_modules.cli_tools import limpar_tela, select_op, verde

import os

args = docopt(__doc__)

@check_config_existance
def main():
    while True:
        limpar_tela()
        print(verde("Selecione uma ação..."))
        op = select_op(['Registrar atendimento', 'Listar estudantes', 'Listar atendimentos', 'Sair'], 1)
        
        if op == 'Registrar atendimento':
            limpar_tela()
            identificador = input(verde("Identificador")+': ')
            print('')
            os.system('novo atd "{}"'.format(identificador))
        
        elif op == 'Listar estudantes':
            limpar_tela()
            filtro = input(verde("Expressão de filtragem")+': ')
            print('')
            os.system('lst usr | grep "{}" | less'.format(filtro))
        
        elif op == 'Listar atendimentos':
            limpar_tela()
            filtro = input(verde("Expressão de filtragem")+': ')
            print('')
            os.system('lst atd | grep "{}" | less'.format(filtro))

        elif op == 'Sair':
            break                        
   

if __name__ == '__main__':
    main()
