#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Insere, altera ou lê informações do usuário alvo corrente, '.current_target'.
Ao utilizar o comando 'novo' para realizar inserções, as informações do usuario alvo são armazenadas no arquivo '.current_target'.

Usage:
    target ( set | edit ) <campo> <valor>
    target ( get ) <campo>

"""

import os

from docopt import docopt
from python_modules.py_functions_json import load_json, save_json
from python_modules.cli_sps_base import pasta_do_usuario

args = docopt(__doc__)

def main():
    if args['set'] or args['edit']:
        current_target = load_json(os.sep.join([pasta_do_usuario, '.current_target']))
        current_target[args['<campo>']] = args['<valor>']
        save_json(current_target, os.sep.join([pasta_do_usuario, '.current_target']))

    elif args['get']:
        current_target = load_json(os.sep.join([pasta_do_usuario, '.current_target']))
        print(current_target.get(args['<campo>']))


 
if __name__ == '__main__':
	main()


