#!/bin/sh

#
# Seleciona colunas do arquivo CSV alvo e converte o delimitador no arquivo de saída para tabulação
#


warning () {
    printf "Usage:\n"
    printf "    csv2tsv <target_file> <delimiter>\n"
}

full_info () {
    printf "\n"
    printf "Comando para edição simplificada de arquivos CSV.\n"
    printf "\n"
    warning
    printf "\n"
    printf "Options:\n"
    printf "    -h, --help\n"
    printf "\n"
}

if [ $# -le 1 ];
then
    warning
    exit
fi

head "$1" -n 1

printf "\nIndique o número das colunas que deverão ser copiadas para o arquivo de saída:"
read -r COLUNAS

LINHAS=$(wc -l < "$1")

c=1
while [ "$c" != "$LINHAS" ]
do
    head "$1" -n $c | tail -n 1 | cut -d "$2" -f $COLUNAS | tr "$2" '\t' >> output.csv
    printf "$c/$LINHAS\n"
    c=$(($c + 1))
done
