#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Cria os diretórios e arquivos de dados conforme a estrutura inicialmente pensadapelo aplicativo.

Usage:
    sps-install ( createdb ) <folder>
    sps-install ( backupdb ) <folder>
    sps-install ( restoredb ) <folder>        
    sps-install ( config ) 

"""

from docopt import docopt
from subprocess import getoutput
from python_modules.cli_decorators import check_config_existance
from python_modules.cli_db_manager import create_db_files, create_user_configuration, backup_db

import os

args = docopt(__doc__)


def main():
    if args['config']:
        create_user_configuration()

    
    elif args['createdb']:
        create_db_files(args["<folder>"])

    elif args['backupdb']:
        backup_db(args["<folder>"])

   

if __name__ == '__main__':
    main()
