#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Descriptografa o arquivo alvo.

Usage:
    sps-decrypt ( <arquivo> ) 

"""

from docopt import docopt
from os import system
from python_modules.cli_db_loader import pasta_de_seguranca

args = docopt(__doc__)

def main():
    system("ccdecrypt {} -k {}/ccrypt-key".format(args['<arquivo>'], pasta_de_seguranca))

if __name__ == '__main__':
    main()
