#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""

Inicia servidor Node.js e outros serviços.

Usage:
    initsrv

Options:
    -v, --version

"""

import os

from docopt import docopt
from subprocess import getoutput

args = docopt(__doc__)
initdir = getoutput('pwd')


def main():
    newid = os.fork()
    if newid == 0:
        print('Iniciando Node.Js...')
        os.system('node index.js')
    else:
        os.system('echo "Iniciando subprocesso..."')
        
if __name__ == '__main__':
    main()
